server:
  port: 8088
  tomcat:
    max-http-form-post-size: -1

spring:
  http:
    default-encoding: utf-8
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exam?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 123456
  devtools:
    add-properties: false

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.frame.model

upload:
  base:
    dir: /mnt